version: '3.9'

services:
    mongo:
       container_name: mongo
       image: mongo:latest
       restart: unless-stopped
       ports:
         -  27017:27017
       volumes:
         - ./data:/data/db
    app:
      container_name: app
     #image: node:16-alpine
      build: .
      restart: always
      ports:
        -  8000:8000
      links: 
        - mongo
      depends_on:
        - mongo
   
volumes:
  data: 