version: '3.9'

services:
      web:
        container_name: nodeapi
        restart: always
        build: .
        ports:
          -  8000:8000
        links: 
          - mongo
        depends_on:
          - mongo
        volumes:
           - .:/usr/src/app
      mongo:
         container_name: mogodatabase
         image: mongo:latest
         restart: always
         ports:
           -  27017:27017
         volumes:
           - data:/data/db
  
volumes:
   data: 